server:
  port: 8088
spring:
  application:
    name: best4u-gateway-service
  cloud:
    gateway:
      routes:
        - id: best4u-configuration
          uri: lg://best4u-configuration
          predicates:
             -  Path=/users/**  
  main:
    web-application-type: reactive
  
eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/
    register-with-eureka: true
    fetch-registry: true
